LLM:
  model_path_or_repo_id: hungsvdut2k2/vistral-rank-16
  model_file: vistral-rank-16-unsloth.Q4_K_M.gguf
  model_type: mistral
  context_length: 4096
  gpu_layers: 100
  top_k: 40
  top_p: 0.95
  temperature: 0.9
  stream: False

Memory:
  top_k: 10

VectorStore:
  host_url: http://127.0.0.1:6333
  model_name: VoVanPhuc/sup-SimCSE-VietNamese-phobert-base
  collection: test-collection